name: stok_abunawas
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  qr_flutter: ^4.1.0
  mobile_scanner: ^4.0.1
  pdf: ^3.11.3
  printing: ^5.12.0
  flutter_svg: ^2.0.10+1
  excel: ^4.0.6
  flutter_file_saver: 0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/stockin/
    - assets/login/
    - assets/stockout/
    - assets/batch/
    - assets/transaction/
    - assets/branding/