// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAavT1ZASAh5g6svMbmBQAFfLAQ9EYzBpU',
    appId: '1:554054643915:web:5b7da964824dbb5ce32b4e',
    messagingSenderId: '554054643915',
    projectId: 'stok-abunawas',
    authDomain: 'stok-abunawas.firebaseapp.com',
    storageBucket: 'stok-abunawas.firebasestorage.app',
    measurementId: 'G-T0ETX5XQG9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFJJNdnxdZZflNpl_0gXUEm5v9fUxTnp4',
    appId: '1:554054643915:android:cf4f54c02cfc5527e32b4e',
    messagingSenderId: '554054643915',
    projectId: 'stok-abunawas',
    storageBucket: 'stok-abunawas.firebasestorage.app',
  );
}
